sudo: false

git:
  submodules: false

language: node_js

notifications:
  email:
  - hust2012jiangkai@gmail.com
  - hualei5280@gmail.com
  - zhang740@qq.com
  - rjmuqiang@gmail.com

node_js:
  - "12"

env:
  matrix:
    - TEST_TYPE=lint
    - TEST_TYPE=compile
    - TEST_TYPE=test

script:
  - |
    if [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = compile ]; then
      npm run compile && \
      LIB_DIR=lib npm run test -- -w 2 && \
      LIB_DIR=es npm run test -- -w 2
    elif [ "$TEST_TYPE" = test ]; then
      npm run test -- -w 2 --coverage && \
      bash <(curl -s https://codecov.io/bash) -cF rn
    fi
